### ISSUE TITLE
[more demo code for how to use it]

### ISSUE THREAD

**Issue by k3mlol** [chaitin/blazehttp#11]
### Describe the feature request

Hi, could you  add some demo code how to import and use it as library?

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [X] Test and Release
- [ ] Developer Infrastructure
- [ ] Others

**Comment by phxa1** [comment]
可以参考cmd/blazehttp/main.go中的使用方式

**Comment by k3mlol** [comment]
thank you
