### ISSUE TITLE
-t 参数不支持默认端口

### ISSUE THREAD

**Issue by naocanmonster** [chaitin/blazehttp#3]
### Bug Description

-t 参数不支持默认端口

现在对于目标需要输入端口号，不太友好

对于 http 和 https 协议应该默认 80 和 443 端口

### System Architecture

all

### Steps to reproduce

1. 
2. 
3. 
...

**Comment by kingfs** [comment]
fix: https://github.com/chaitin/blazehttp/commit/aaa87737c231a0d98e0dfef3db9a1408fda7ddda
