### ISSUE TITLE
用Mac测试工具的时候，中间会出现很多空行

### ISSUE THREAD

**Issue by gandhi3** [chaitin/blazehttp#6]
### Bug Description

<img width="919" alt="image" src="https://github.com/chaitin/blazehttp/assets/47944780/1ed14633-d647-4920-b078-76d04a74355f">

### System Architecture

Mac/M1

### Steps to reproduce

1. 
2. 
3. 
...

**Comment by kingfs** [comment]
已经确认是processbar的默认配置导致的，已经修复：https://github.com/chaitin/blazehttp/pull/9
